---
collections:
  - name: redhat.satellite_operations

  - name: redhat.satellite

  - name: theforeman.foreman
    source: https://galaxy.ansible.com

  - name: theforeman.operations
    source: https://galaxy.ansible.com
